version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traffic_backend
    env_file:
      - .env.docker
    ports:
      - "8002:8000"
    volumes:
      - ./storage:app/storage
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg16
    container_name: traffic_postgres
    environment:
      POSTGRES_DB: traffic_project
      POSTGRES_USER: traffic_agent
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
