"""add upload batch id to simulation run

Revision ID: d2fe2a180b51
Revises: ef53a0620b17
Create Date: 2026-08-06 11:13:17.035627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2fe2a180b51'
down_revision: Union[str, Sequence[str], None] = 'ef53a0620b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_runs', sa.Column('upload_batch_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_simulation_runs_upload_batch_id'), 'simulation_runs', ['upload_batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_runs_upload_batch_id'), table_name='simulation_runs')
    op.drop_column('simulation_runs', 'upload_batch_id')
    # ### end Alembic commands ###
