"""clean user model and create file trash

Revision ID: de5274a701db
Revises: 5a0883e5a608
Create Date: 2026-08-10 15:14:53.948328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de5274a701db'
down_revision: Union[str, Sequence[str], None] = '5a0883e5a608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_trash',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=64), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('original_path', sa.String(length=1024), nullable=False),
    sa.Column('trash_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_trash_batch_id'), 'file_trash', ['batch_id'], unique=False)
    op.create_index(op.f('ix_file_trash_id'), 'file_trash', ['id'], unique=False)
    op.create_index(op.f('ix_file_trash_simulation_id'), 'file_trash', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_file_trash_user_id'), 'file_trash', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_role_id'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_role_id'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_user_id'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_roles_description'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_agent_messages_create_at'), table_name='agent_messages')
    op.create_index(op.f('ix_agent_messages_created_at'), 'agent_messages', ['created_at'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'email')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('ADMIN', 'USER', name='userrole'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_agent_messages_created_at'), table_name='agent_messages')
    op.create_index(op.f('ix_agent_messages_create_at'), 'agent_messages', ['created_at'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_builtin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('roles_pkey'))
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_description'), 'roles', ['description'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('user_role_role_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_role_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_role_pkey')),
    sa.UniqueConstraint('user_id', 'role_id', name=op.f('uq_user_role_user_id_role_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_role_user_id'), 'user_role', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_role_role_id'), 'user_role', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_role_id'), 'user_role', ['id'], unique=False)
    op.drop_index(op.f('ix_file_trash_user_id'), table_name='file_trash')
    op.drop_index(op.f('ix_file_trash_simulation_id'), table_name='file_trash')
    op.drop_index(op.f('ix_file_trash_id'), table_name='file_trash')
    op.drop_index(op.f('ix_file_trash_batch_id'), table_name='file_trash')
    op.drop_table('file_trash')
    # ### end Alembic commands ###
